name: app-b
on:
  push:
    # only run when app-* changes, or in this workflow file changes, or package.json changes
    paths:
      - 'packages/app-b/**'
      - .github/workflows/app-b.yml
      - package.json

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
          
      # run tests against app-*
      # wait for app-* to be served before starting the tests
      # run tests against packages/app-* folder
      - name: Cypress e2e tests 🧪
        uses: cypress-io/github-action@v2.11.7
        with:
          start: yarn start:b
          wait-on: 'http://localhost:3000'
          project: ./packages/app-b
          record: true
          tag: e2e-test
          group: e2e
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          
      - name: Cypress component tests 🧪
        uses: cypress-io/github-action@v2.11.7
        with:
          # we have already installed everything
          install: false
          # to run component tests we need to use "cypress run-ct"
          command: yarn cypress run-ct
          project: ./packages/app-b
          browser: chrome
          record: true
          tag: comp-test
          group: component
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
    

