name: app-b
on:
  push:

jobs:
  # https://microsoft.github.io/code-with-engineering-playbook/continuous-delivery/devops-provider-recipes/github-actions/runtime-variables/runtime-variables/
  Echo-On-Commit:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v2

      - name: "Set an environment variable"
        # contains is a GitHub Actions function that is available by default in all workflows. It returns a Boolean true or false value. 
        # Here, it checks to see if the commit message on the last push, accessed using github.event.head_commit.message. 
        # The ${{...}} is necessary to use the GitHub Context and make the functions and github.event variables available for the command.
        env:
          BASE_URL_EXISTS: ${{ contains(github.event.head_commit.message, 'baseUrl=') }}
          BASEURL_REGEX: '(http:\/\/|https:\/\/)?[^\/\?]*$'
          COMMIT_MSG: "$(git log --oneline -1)"
        # The run command here checks to see if the BASE_URL_EXISTSvariable has been set to true,
        # and if it has, it sets a secondary flag to true, and echoes this behavior. 
        # It does the same if the variable is false.
        # Setting an environment variable 
        # echo "{environment_variable_name}={value}" >> $GITHUB_ENV
  
        run: |
          if [[ ${BASE_URL_EXISTS} == true ]] && [[ ${{ env.COMMIT_MSG }} =~ ${{ env.BASEURL_REGEX }} ]] ; then
            echo "something great worked"
          else
            echo "baseUrl not specified, using the config file"
          fi
      # The specific reason to do this is to allow for the flag variable to be used in further steps instead of having to reuse the BASE_URL_EXISTS in every step. 
      # Further, it allows for the flag to be used in the if step of an action, as in the next part of the snippet.
      - name: "Output the baseUrl"
        if: env.baseUrl
        run: echo "baseUrl is ${{ env.baseUrl }}"

  files-changed:
    name: Determine if files changed
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: changes
        with: 
          filters: |
            src: 
              - packages/app-b/**
              - .github/workflows/app-c.yml
              - package.json
    outputs:
      filesChanged: ${{ steps.changes.outputs.src }}

  test:
    needs: [files-changed]
    if: needs.files-changed.outputs.filesChanged == 'true'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      # run tests against app-*
      # wait for app-* to be served before starting the tests
      # run tests against packages/app-* folder
      - name: Cypress tests 🧪
        uses: cypress-io/github-action@v2
        with:
          start: yarn start:b
          wait-on: 'http://localhost:3000'
          project: ./packages/app-b
          browser: chrome
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
