name: app-b
on:
  push:
    # only run when app-a changes, or in this workflow file changes, or package.json changes
    paths:
      - 'packages/app-b/**'
      - .github/workflows/app-b.yml
      - package.json
      - README.md # to test them running simultaneously

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
          
      # run tests against app-*
      # wait for app-* to be served before starting the tests
      # run tests against packages/app-* folder
      - name: Cypress tests 🧪
        uses: cypress-io/github-action@v2
        with:
          start: yarn start:b
          wait-on: 'http://localhost:3000'
          project: ./packages/app-b
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          
          

