name: app-b
on:
  push:

jobs:
  files-changed:
    name: Determine if files changed
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: changes
        with: 
          filters: |
            src: 
              - packages/app-c/**
              - .github/workflows/app-c.yml
              - package.json
    outputs:
      filesChanged: ${{ steps.changes.outputs.src }}

  test:
    needs: [files-changed]
    if: needs.files-changed.outputs.filesChanged == 'true'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      # run tests against app-*
      # wait for app-* to be served before starting the tests
      # run tests against packages/app-* folder
      - name: Cypress tests 🧪
        uses: cypress-io/github-action@v2
        with:
          start: yarn start:b
          wait-on: 'http://localhost:3000'
          project: ./packages/app-b
          browser: chrome
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
