name: repeat-tag-called

on:
  workflow_call:
    inputs:
      start-command:
        required: true
        type: string
      project-directory:
        required: true
        type: string
      tag:
        required: true
        type: string
      times:
        required: false
        type: string

jobs:
  repeat_tag:
    runs-on: ubuntu-20.04
    steps:
      - name: Print workflow inputs
        run: |
          echo Running with start-command: ${{ inputs.start-command }}
          echo On project directory: ${{ inputs.project-directory }}
          echo With tag: ${{ inputs.tag }}
          echo For ${{ inputs.times }} times

      - name: Checkout 🛎
        uses: actions/checkout@v3

      # https://github.com/cypress-io/github-action
      - name: Run the tag N times
        uses: cypress-io/github-action@v3
        with:
          start: ${{ inputs.start-command }}
          wait-on: 'http://localhost:3000'
          project: ${{ inputs.project-directory }}
          browser: chrome
          env: 'grepTags="${{ inputs.tag }}",burn=${{ inputs.times }}'
