# https://github.com/bahmutov/test-todomvc-using-app-actions/blob/master/.github/workflows/repeat-test.yml

name: repeat-c-tag
on:
  workflow_dispatch:
    description: Lets the user run a spec file N times in a row
    inputs:
      tag:
        description: Tag to run
        required: true
        type: choice
        options:
          - '@c'
      n:
        description: Number of times to repeat the test
        required: false
        default: '1'
        type: string

jobs:
  repeat-c-tag:
    runs-on: ubuntu-20.04
    steps:
      - name: Print workflow inputs
        run: |
          echo Running tests with tag: ${{ github.event.inputs.tag }}
          echo for ${{ github.event.inputs.n }} times

      - name: Checkout 🛎
        uses: actions/checkout@v3

      # https://github.com/cypress-io/github-action
      - name: Run the spec N times
        uses: cypress-io/github-action@v5.0.5
        with:
          start: yarn start:c
          wait-on: 'http://localhost:3000'
          project: ./packages/app-c
          browser: chrome
          env: 'grepTags=${{ github.event.inputs.tag }},burn=${{ github.event.inputs.n }}'
